import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavbarCustom from "../components/shared/navbarCustom";
import ReduxProvider from "../redux/provider";
import { Providers } from "./Providers";
import "./globals.css";
import { AuthProvider } from "@/providers/auth.provider";
import PrivateRoute from "@/utils/privateRoute";
import { Component } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   const protectedRoutes = ["/home"];

   return (
      <html lang="en">
         <body className={inter.className}>
            <Providers>
               <NavbarCustom />
               <ReduxProvider>
                  {/* <AuthProvider> */}
                     {/* <PrivateRoute protectedRoutes={protectedRoutes}> */}
                        {children}
                     {/* </PrivateRoute> */}
                  {/* </AuthProvider> */}
               </ReduxProvider>
            </Providers>
         </body>
      </html>
   );
}
